#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CreateLoginUserLibrary.Resource", IsApplication=false)]

namespace CreateLoginUserLibrary
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public static int Gender = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public static int clulCreateBirthdateTextView = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public static int clulCreateEmailAddressEditText = 2131034127;
			
			// aapt resource value: 0x7f050009
			public static int clulCreateFirstNameEditText = 2131034121;
			
			// aapt resource value: 0x7f050012
			public static int clulCreateGenderSpinner = 2131034130;
			
			// aapt resource value: 0x7f05000c
			public static int clulCreateLastNameEditText = 2131034124;
			
			// aapt resource value: 0x7f050006
			public static int clulCreatePasswordEditText = 2131034118;
			
			// aapt resource value: 0x7f05001f
			public static int clulCreateUserButton1 = 2131034143;
			
			// aapt resource value: 0x7f050016
			public static int clulCreateUserButton2 = 2131034134;
			
			// aapt resource value: 0x7f050003
			public static int clulCreateUserNameEditText = 2131034115;
			
			// aapt resource value: 0x7f05001e
			public static int clulLoginButton = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public static int clulLoginPasswordEditText = 2131034141;
			
			// aapt resource value: 0x7f05001a
			public static int clulLoginUserNameEditText = 2131034138;
			
			// aapt resource value: 0x7f050017
			public static int clulTableLayout1 = 2131034135;
			
			// aapt resource value: 0x7f050000
			public static int clulTableLayout2 = 2131034112;
			
			// aapt resource value: 0x7f050018
			public static int clulTableRow1 = 2131034136;
			
			// aapt resource value: 0x7f050001
			public static int clulTableRow10 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public static int clulTableRow11 = 2131034116;
			
			// aapt resource value: 0x7f050007
			public static int clulTableRow12 = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public static int clulTableRow13 = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public static int clulTableRow14 = 2131034125;
			
			// aapt resource value: 0x7f050010
			public static int clulTableRow15 = 2131034128;
			
			// aapt resource value: 0x7f050013
			public static int clulTableRow16 = 2131034131;
			
			// aapt resource value: 0x7f050019
			public static int clulTextView1 = 2131034137;
			
			// aapt resource value: 0x7f050002
			public static int clulTextView10 = 2131034114;
			
			// aapt resource value: 0x7f050005
			public static int clulTextView11 = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public static int clulTextView13 = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public static int clulTextView14 = 2131034126;
			
			// aapt resource value: 0x7f050011
			public static int clulTextView15 = 2131034129;
			
			// aapt resource value: 0x7f050014
			public static int clulTextView16 = 2131034132;
			
			// aapt resource value: 0x7f05001c
			public static int clulTextView2 = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public static int tableRow2 = 2131034139;
			
			// aapt resource value: 0x7f050008
			public static int textView12 = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int Create = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int Login = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public static int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
