#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AlbumsSample.Resource", IsApplication=true)]

namespace AlbumsSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CreateLoginUserLibrary.Resource.Array.Gender = global::AlbumsSample.Resource.Array.Gender;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateBirthdateTextView = global::AlbumsSample.Resource.Id.clulCreateBirthdateTextView;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateEmailAddressEditText = global::AlbumsSample.Resource.Id.clulCreateEmailAddressEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateFirstNameEditText = global::AlbumsSample.Resource.Id.clulCreateFirstNameEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateGenderSpinner = global::AlbumsSample.Resource.Id.clulCreateGenderSpinner;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateLastNameEditText = global::AlbumsSample.Resource.Id.clulCreateLastNameEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulCreatePasswordEditText = global::AlbumsSample.Resource.Id.clulCreatePasswordEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateUserButton1 = global::AlbumsSample.Resource.Id.clulCreateUserButton1;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateUserButton2 = global::AlbumsSample.Resource.Id.clulCreateUserButton2;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateUserNameEditText = global::AlbumsSample.Resource.Id.clulCreateUserNameEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulLoginButton = global::AlbumsSample.Resource.Id.clulLoginButton;
			global::CreateLoginUserLibrary.Resource.Id.clulLoginPasswordEditText = global::AlbumsSample.Resource.Id.clulLoginPasswordEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulLoginUserNameEditText = global::AlbumsSample.Resource.Id.clulLoginUserNameEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulTableLayout1 = global::AlbumsSample.Resource.Id.clulTableLayout1;
			global::CreateLoginUserLibrary.Resource.Id.clulTableLayout2 = global::AlbumsSample.Resource.Id.clulTableLayout2;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow1 = global::AlbumsSample.Resource.Id.clulTableRow1;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow10 = global::AlbumsSample.Resource.Id.clulTableRow10;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow11 = global::AlbumsSample.Resource.Id.clulTableRow11;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow12 = global::AlbumsSample.Resource.Id.clulTableRow12;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow13 = global::AlbumsSample.Resource.Id.clulTableRow13;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow14 = global::AlbumsSample.Resource.Id.clulTableRow14;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow15 = global::AlbumsSample.Resource.Id.clulTableRow15;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow16 = global::AlbumsSample.Resource.Id.clulTableRow16;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView1 = global::AlbumsSample.Resource.Id.clulTextView1;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView10 = global::AlbumsSample.Resource.Id.clulTextView10;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView11 = global::AlbumsSample.Resource.Id.clulTextView11;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView13 = global::AlbumsSample.Resource.Id.clulTextView13;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView14 = global::AlbumsSample.Resource.Id.clulTextView14;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView15 = global::AlbumsSample.Resource.Id.clulTextView15;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView16 = global::AlbumsSample.Resource.Id.clulTextView16;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView2 = global::AlbumsSample.Resource.Id.clulTextView2;
			global::CreateLoginUserLibrary.Resource.Id.tableRow2 = global::AlbumsSample.Resource.Id.tableRow2;
			global::CreateLoginUserLibrary.Resource.Id.textView12 = global::AlbumsSample.Resource.Id.textView12;
			global::CreateLoginUserLibrary.Resource.Layout.Create = global::AlbumsSample.Resource.Layout.Create;
			global::CreateLoginUserLibrary.Resource.Layout.Login = global::AlbumsSample.Resource.Layout.Login;
			global::CreateLoginUserLibrary.Resource.String.library_name = global::AlbumsSample.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int Gender = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int addPictureButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int albumItemsGridView = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int albumsListView = 2131034117;
			
			// aapt resource value: 0x7f05001b
			public const int clulCreateBirthdateTextView = 2131034139;
			
			// aapt resource value: 0x7f050015
			public const int clulCreateEmailAddressEditText = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public const int clulCreateFirstNameEditText = 2131034127;
			
			// aapt resource value: 0x7f050018
			public const int clulCreateGenderSpinner = 2131034136;
			
			// aapt resource value: 0x7f050012
			public const int clulCreateLastNameEditText = 2131034130;
			
			// aapt resource value: 0x7f05000c
			public const int clulCreatePasswordEditText = 2131034124;
			
			// aapt resource value: 0x7f050025
			public const int clulCreateUserButton1 = 2131034149;
			
			// aapt resource value: 0x7f05001c
			public const int clulCreateUserButton2 = 2131034140;
			
			// aapt resource value: 0x7f050009
			public const int clulCreateUserNameEditText = 2131034121;
			
			// aapt resource value: 0x7f050024
			public const int clulLoginButton = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int clulLoginPasswordEditText = 2131034147;
			
			// aapt resource value: 0x7f050020
			public const int clulLoginUserNameEditText = 2131034144;
			
			// aapt resource value: 0x7f05001d
			public const int clulTableLayout1 = 2131034141;
			
			// aapt resource value: 0x7f050006
			public const int clulTableLayout2 = 2131034118;
			
			// aapt resource value: 0x7f05001e
			public const int clulTableRow1 = 2131034142;
			
			// aapt resource value: 0x7f050007
			public const int clulTableRow10 = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int clulTableRow11 = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int clulTableRow12 = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int clulTableRow13 = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int clulTableRow14 = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int clulTableRow15 = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int clulTableRow16 = 2131034137;
			
			// aapt resource value: 0x7f05001f
			public const int clulTextView1 = 2131034143;
			
			// aapt resource value: 0x7f050008
			public const int clulTextView10 = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int clulTextView11 = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int clulTextView13 = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int clulTextView14 = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int clulTextView15 = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int clulTextView16 = 2131034138;
			
			// aapt resource value: 0x7f050022
			public const int clulTextView2 = 2131034146;
			
			// aapt resource value: 0x7f050003
			public const int createAlbumButton = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int createAlbumEditText = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int horizontalLinearLayout = 2131034114;
			
			// aapt resource value: 0x7f050021
			public const int tableRow2 = 2131034145;
			
			// aapt resource value: 0x7f05000e
			public const int textView12 = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AlbumItems = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Albums = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Create = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Login = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
