#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CreateLoginUserSample.Resource", IsApplication=true)]

namespace CreateLoginUserSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CreateLoginUserLibrary.Resource.Array.Gender = global::CreateLoginUserSample.Resource.Array.Gender;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateBirthdateTextView = global::CreateLoginUserSample.Resource.Id.clulCreateBirthdateTextView;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateEmailAddressEditText = global::CreateLoginUserSample.Resource.Id.clulCreateEmailAddressEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateFirstNameEditText = global::CreateLoginUserSample.Resource.Id.clulCreateFirstNameEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateGenderSpinner = global::CreateLoginUserSample.Resource.Id.clulCreateGenderSpinner;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateLastNameEditText = global::CreateLoginUserSample.Resource.Id.clulCreateLastNameEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulCreatePasswordEditText = global::CreateLoginUserSample.Resource.Id.clulCreatePasswordEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateUserButton1 = global::CreateLoginUserSample.Resource.Id.clulCreateUserButton1;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateUserButton2 = global::CreateLoginUserSample.Resource.Id.clulCreateUserButton2;
			global::CreateLoginUserLibrary.Resource.Id.clulCreateUserNameEditText = global::CreateLoginUserSample.Resource.Id.clulCreateUserNameEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulLoginButton = global::CreateLoginUserSample.Resource.Id.clulLoginButton;
			global::CreateLoginUserLibrary.Resource.Id.clulLoginPasswordEditText = global::CreateLoginUserSample.Resource.Id.clulLoginPasswordEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulLoginUserNameEditText = global::CreateLoginUserSample.Resource.Id.clulLoginUserNameEditText;
			global::CreateLoginUserLibrary.Resource.Id.clulTableLayout1 = global::CreateLoginUserSample.Resource.Id.clulTableLayout1;
			global::CreateLoginUserLibrary.Resource.Id.clulTableLayout2 = global::CreateLoginUserSample.Resource.Id.clulTableLayout2;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow1 = global::CreateLoginUserSample.Resource.Id.clulTableRow1;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow10 = global::CreateLoginUserSample.Resource.Id.clulTableRow10;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow11 = global::CreateLoginUserSample.Resource.Id.clulTableRow11;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow12 = global::CreateLoginUserSample.Resource.Id.clulTableRow12;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow13 = global::CreateLoginUserSample.Resource.Id.clulTableRow13;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow14 = global::CreateLoginUserSample.Resource.Id.clulTableRow14;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow15 = global::CreateLoginUserSample.Resource.Id.clulTableRow15;
			global::CreateLoginUserLibrary.Resource.Id.clulTableRow16 = global::CreateLoginUserSample.Resource.Id.clulTableRow16;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView1 = global::CreateLoginUserSample.Resource.Id.clulTextView1;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView10 = global::CreateLoginUserSample.Resource.Id.clulTextView10;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView11 = global::CreateLoginUserSample.Resource.Id.clulTextView11;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView13 = global::CreateLoginUserSample.Resource.Id.clulTextView13;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView14 = global::CreateLoginUserSample.Resource.Id.clulTextView14;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView15 = global::CreateLoginUserSample.Resource.Id.clulTextView15;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView16 = global::CreateLoginUserSample.Resource.Id.clulTextView16;
			global::CreateLoginUserLibrary.Resource.Id.clulTextView2 = global::CreateLoginUserSample.Resource.Id.clulTextView2;
			global::CreateLoginUserLibrary.Resource.Id.tableRow2 = global::CreateLoginUserSample.Resource.Id.tableRow2;
			global::CreateLoginUserLibrary.Resource.Id.textView12 = global::CreateLoginUserSample.Resource.Id.textView12;
			global::CreateLoginUserLibrary.Resource.Layout.Create = global::CreateLoginUserSample.Resource.Layout.Create;
			global::CreateLoginUserLibrary.Resource.Layout.Login = global::CreateLoginUserSample.Resource.Layout.Login;
			global::CreateLoginUserLibrary.Resource.String.library_name = global::CreateLoginUserSample.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int Gender = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002e
			public const int birthdateTextView = 2131099694;
			
			// aapt resource value: 0x7f060015
			public const int clulCreateBirthdateTextView = 2131099669;
			
			// aapt resource value: 0x7f06000f
			public const int clulCreateEmailAddressEditText = 2131099663;
			
			// aapt resource value: 0x7f060009
			public const int clulCreateFirstNameEditText = 2131099657;
			
			// aapt resource value: 0x7f060012
			public const int clulCreateGenderSpinner = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int clulCreateLastNameEditText = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int clulCreatePasswordEditText = 2131099654;
			
			// aapt resource value: 0x7f06001f
			public const int clulCreateUserButton1 = 2131099679;
			
			// aapt resource value: 0x7f060016
			public const int clulCreateUserButton2 = 2131099670;
			
			// aapt resource value: 0x7f060003
			public const int clulCreateUserNameEditText = 2131099651;
			
			// aapt resource value: 0x7f06001e
			public const int clulLoginButton = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int clulLoginPasswordEditText = 2131099677;
			
			// aapt resource value: 0x7f06001a
			public const int clulLoginUserNameEditText = 2131099674;
			
			// aapt resource value: 0x7f060017
			public const int clulTableLayout1 = 2131099671;
			
			// aapt resource value: 0x7f060000
			public const int clulTableLayout2 = 2131099648;
			
			// aapt resource value: 0x7f060018
			public const int clulTableRow1 = 2131099672;
			
			// aapt resource value: 0x7f060001
			public const int clulTableRow10 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int clulTableRow11 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int clulTableRow12 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int clulTableRow13 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int clulTableRow14 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int clulTableRow15 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int clulTableRow16 = 2131099667;
			
			// aapt resource value: 0x7f060019
			public const int clulTextView1 = 2131099673;
			
			// aapt resource value: 0x7f060002
			public const int clulTextView10 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int clulTextView11 = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int clulTextView13 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int clulTextView14 = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int clulTextView15 = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int clulTextView16 = 2131099668;
			
			// aapt resource value: 0x7f06001c
			public const int clulTextView2 = 2131099676;
			
			// aapt resource value: 0x7f060028
			public const int emailAddressTextView = 2131099688;
			
			// aapt resource value: 0x7f060025
			public const int firstLastNameTextView = 2131099685;
			
			// aapt resource value: 0x7f06002b
			public const int genderTextView = 2131099691;
			
			// aapt resource value: 0x7f060020
			public const int tableLayout1 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int tableRow1 = 2131099681;
			
			// aapt resource value: 0x7f06001b
			public const int tableRow2 = 2131099675;
			
			// aapt resource value: 0x7f060026
			public const int tableRow3 = 2131099686;
			
			// aapt resource value: 0x7f060029
			public const int tableRow4 = 2131099689;
			
			// aapt resource value: 0x7f06002c
			public const int tableRow5 = 2131099692;
			
			// aapt resource value: 0x7f060022
			public const int textView1 = 2131099682;
			
			// aapt resource value: 0x7f060008
			public const int textView12 = 2131099656;
			
			// aapt resource value: 0x7f060024
			public const int textView2 = 2131099684;
			
			// aapt resource value: 0x7f060027
			public const int textView3 = 2131099687;
			
			// aapt resource value: 0x7f06002a
			public const int textView4 = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int textView5 = 2131099693;
			
			// aapt resource value: 0x7f060023
			public const int userNameTextView = 2131099683;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Create = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Login = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int View = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int app_name = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int DefaultTextViewStyle = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int DefaultTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
